devtest:
  greeting: "hello"
---
spring:
  profiles: stage
devtest: 
  greeting: "stage server"
---
spring:
  profiles: dev
devtest: 
  greeting: "dev server hello"
---
spring:
  profiles: local
devtest: 
  greeting: "local server"
